### ISSUE TITLE
Investigate requests to /undefined

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-web#16]
For some reason, the app makes random requests to `/undefined` (note that those requests are made to the webserver itself, not to the API) : 
![image](https://user-images.githubusercontent.com/3159134/77559016-f36a6f80-6ebb-11ea-86ba-f1cd696300f5.png)

We should investigate and track down those undefined requests. It does not make the app crash but it adds some noise and overhead.

:male_detective: :female_detective:

**Comment by micedre** [comment]
The exact request is for an image : 
```
GET /undefined HTTP/1.1
Host: spyrales.sspcloud.fr
Connection: keep-alive
Accept: image/webp,image/apng,image/*,*/*;q=0.8
```
In the html we see `<link id="favicon" type="image/png" rel="shortcut icon" href="undefined">`

I think it should be enough to add `%PUBLIC_URL%` to the `href` attribute here : 
https://github.com/InseeFrLab/onyxia-ui/blob/master/public/index.html#L10

**Comment by olevitt** [comment]
Nice !

I confirmed that the issue is due to this.  
Adding `%PUBLIC_URL%` helps but the issue still persists due to the `Favicon` component https://github.com/InseeFrLab/onyxia-ui/blob/master/src/js/components/commons/favicon/index.js that dynamically changes the favicon based on the state of the app.  
We should decide what to do next : either keeping the Favicon component logic and fixing it or get rid of it.  

Any input on this ?
