### ISSUE TITLE
New feature : Mon labo - save contracts definition

### ISSUE THREAD

**Issue by labenech** [InseeFrLab/onyxia-web#163]
Hi,
I think that the option of saving/edit  most used contracts def could be a great improvement in UI experience !

**Comment by fcomte** [comment]
hello,

At the moment, we offer a link that all user can save elsewhere to start easily a new contracts. This is the way to create formation or thing like that.

For the user experience, we can maybe offer a save button, (save it inside Vault), and show a new panel with a list of shortcuts.
What do you think about that ?

**Comment by labenech** [comment]
Yes ... That's exactly what I mean !!!

**Comment by romaintailhurat** [comment]
Same need here, but with a slightly different take. I think we have several options here:
- having a "pin" or save feature
- having a list of the N previous used services
- having a list of the N most used services of a period

I could materialize as a section over the list of catalogs in the catalog UI. It could also be news items in the floating shorcut bar (bottom right corner).
