### ISSUE TITLE
Mon compte page doesn't load

### ISSUE THREAD

**Issue by MelineeTS** [InseeFrLab/onyxia-web#164]
issue : an user - without first name nor last name stored in keycloak - tries to go in mon-compte page. This page appears for less than 1s and after there is only  a white page.
We have to anticipate this possibility.

**Comment by garronej** [comment]
Noted. You self assigned this issue, does it mean that you plan to fix it on master? 
IMO it can wait until my refactor is complete. It should fix a lot of theses types related issues...   

Thanks for reporting
