### ISSUE TITLE
RPGD  : we should ask user to validate term of conditions. 

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-web#165]
Agreement should be store in vault and versionned.
Anytime a user login we should show term of conditions if current version differ from the one store in his vault.
We can think about vault ACL to not allow a user to delete his agreement.

**Comment by micedre** [comment]
You can do it with keycloak
https://www.keycloak.org/docs/latest/server_admin/index.html#terms-and-conditions


Would that be enough, or do you need other things?

**Comment by fcomte** [comment]
It could be a good way to start.

**Comment by fcomte** [comment]
But we should do both.
