### ISSUE TITLE
kaggle integration

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-web#182]
We should manage kaggle integration.
We need to rework "onyxia profile" in separate categories of secure environnement in vault : 
- onyxia env with only a password inside at the moment
- a git env with the 3 git variables that already exist.
- a kaggle environment with 2 variables , username and key api.. that's users can modify

this kaagle environment could be inject in containers (helm or universe)

**Comment by garronej** [comment]
@fcomte Adressed in [PR#184](https://github.com/InseeFrLab/onyxia-ui/pull/184)

**Comment by garronej** [comment]
I forgot the username... will add
