### ISSUE TITLE
My cluster features is broken.

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-web#186]
![image](https://user-images.githubusercontent.com/48868412/100210664-86f0b600-2f0b-11eb-9655-c751368ea19a.png)

The kubernetes api is not defined

**Comment by olevitt** [comment]
This is related to your deployment configuration.  
You should define `KUB_SERVER_URL` env variable for the UI.
Note that this will change in the next major release as we move onto a region-based configuration
