### ISSUE TITLE
Améliorer l'accessibilité des buckets communs sur MinIO

### ISSUE THREAD

**Issue by oliviermeslin** [InseeFrLab/onyxia-web#197]
Bonjour,

Je répercute ici une suggestion de Virginie Gamblin. Le _bucket_ `donnees-insee` est accessible que depuis la page d'accueil du SSP Cloud, mais quand on clique sur `mes fichiers`, on ne voit que son _bucket_ personnel et pas le _bucket_ ouvert à tous. Serait-il possible d'ajouter en dessous de la rubrique "La liste de vos dépôts" une autre rubrique "Les dépôts ouverts à tous", ou quelque chose comme ça, pour faire apparaître sur la même page le _bucket_ `donnees-insee` (et les éventuels autres _buckets_ de données ouvertes à tous les utilisateurs)?

![image](https://user-images.githubusercontent.com/44379737/103646412-e950c380-4f59-11eb-9a9b-86d38a53ac75.png)

**Comment by fcomte** [comment]
On avait mis atlas qui permettra d indexer et chercher des données en lecture seule. C est surtout cette fonction qu il faut qu on remette et valorisé dans le datalab je pense
