### ISSUE TITLE
White page when trying to deploy service without logging in

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/onyxia-web#200]
When accessing https://datalab.sspcloud.fr, and trying to launch a service from the catalog without logging in, we get a white page.

Network view shows the following http requests : 

```
GET https://datalab.sspcloud.fr/accueil

GET https://auth.lab.sspcloud.fr/auth/realms/sspcloud/protocol/openid-connect/auth?client_id=onyxia&redirect_uri=https%3A%2F%2Fdatalab.sspcloud.fr%2Fsilent-sso.html&state=no&response_mode=query&response_type=code&scope=openid&nonce=neither&prompt=none

GET https://datalab.sspcloud.fr/silent-sso.html?error=login_required&state=no
```

I think we should force log in either when accessing catalog, or trying to launch a service.

**Comment by garronej** [comment]
@micedre sure thing, it's coming.
