### ISSUE TITLE
Little detail with typography style alerts

### ISSUE THREAD

**Issue by marchufschmitt** [InseeFrLab/onyxia-web#228]
@garronej https://github.com/InseeFrLab/onyxia-ui/blob/09436b48a4c1edcc7d10102bb497222c8e8bc05b/src/app/components/designSystem/Alert.tsx#L24-L37
<img width="458" alt="Capture d’écran 2021-04-14 à 11 29 38" src="https://user-images.githubusercontent.com/62331119/114689750-507ad280-9d16-11eb-8b17-f23b19b55f9c.png">

Body 1  at the moment

<img width="359" alt="Capture d’écran 2021-04-14 à 11 30 58" src="https://user-images.githubusercontent.com/62331119/114689760-52dd2c80-9d16-11eb-8fcc-75e8f94100cc.png">

Change to Subtitle 2

**Comment by garronej** [comment]
Done (long time ago)
