### ISSUE TITLE
Ip adress is wrong when using uBlock Origin

### ISSUE THREAD

**Issue by micedre** [InseeFrLab/onyxia-web#241]
The public-ip package fetch the public Ip Adress from icanhaz and ipfy services. When using ublock origin (and maybe others ad blocker), those domains are blocked, and the ip adress cannot be retrieved. 
This leads to onyxia filling the ip adress with 0.0.0.0 in services, blocking all access to services when security ip is enabled (by default)

**Comment by micedre** [comment]
https://github.com/rdegges/ipify-api/issues/18

https://github.com/easylist/easylist/issues/2810

**Comment by garronej** [comment]
Damn it. Ok then I will use Onyxia API to fetch the IP then

**Comment by garronej** [comment]
Fixed in 0.11.40. Cool feature side feature. If the ip changes due to user switching to mobile data for example, the ip is reactively updated.

**Comment by garronej** [comment]
Thanks for reporting @micedre
