### ISSUE TITLE
Landscape mode detected on a 4K screen

### ISSUE THREAD

**Issue by mgrzybek** [InseeFrLab/onyxia-web#242]
When a "big screen" is used and vertically splitted, the web browser covers half of the surface, ie. 1920x2160. Although this is pretty huge, the UI is disabled.

Is it possible to detect that a mobile device is not used to allow "ladscape mode" ?

**Comment by garronej** [comment]
Ok I will adress this issue ASAP.  
Currently this message shows as soon as the height of the window is greater that the width wich is what happens with any 16:9 screen split in two.  
I admit this is not ideal

**Comment by garronej** [comment]
Will be fixed in the next release
