### ISSUE TITLE
préremplir identifiant rstudio

### ISSUE THREAD

**Issue by py-b** [InseeFrLab/onyxia-web#244]
Est-il possible de remplir l'username (**rstudio**) à la création d'un service RStudio ?

Ce serait pratique, étant donné que c'est toujours la même chose. De plus, de nombreux utilisateurs débutants bloquent sur ce point.

**Comment by fcomte** [comment]
pas à ma connaissance

**Comment by py-b** [comment]
merci @fcomte, n'hésite pas à fermer cette issue si ça s'avère impossible.

**Comment by fcomte** [comment]
https://docs.rstudio.com/ide/server-pro/authenticating-users.html#customizing-the-sign-in-page

Peut être ca

**Comment by jdlom** [comment]
Salut,
J'ai tenté de custom l'image docker pour monter un fichier HTML dans /etc/rstudio/login.html avec du JavaScript pour preremplir l'identifiant.
Résultat : aucune trace du HTML dans le conteneur. Je n'ai pas plus cherché mais je ne suis pas certain que la version community de rstudio server le permette.

**Comment by fcomte** [comment]
close unresolved
