### ISSUE TITLE
account git

### ISSUE THREAD

**Issue by fcomte** [InseeFrLab/onyxia-web#245]
Users can no more save the time that their git credential should be cache?

Can we add this here ?

![image](https://user-images.githubusercontent.com/48868412/122741172-fb62bc00-d284-11eb-835f-aad3acf3ad57.png)

**Comment by fcomte** [comment]
this value is store in vault with the secret : gitCredentialCacheDuration

**Comment by garronej** [comment]
We removed this field because we assumed 0 (infinity) would always be the preferred default.  
Was there user complaints about it?  
Anyway, sure, I can add it back in if you think it's relevant.

**Comment by fcomte** [comment]
0 is not working. 
There is no cache at the moment.
But anyway I prefer that users can control this security feature

**Comment by garronej** [comment]
What's the correct value for infinity then?

**Comment by fcomte** [comment]
i don't know

**Comment by fcomte** [comment]
but infinity is very bad for security so I really don't like that

**Comment by garronej** [comment]
Considering we have IP protection enabled by default  and a services password I though the the git password was protected enough already...
What do you see as default? 2 hours?

**Comment by fcomte** [comment]
The last default was no cache (0)
I think it's a good default because it's the standard configuration of git.

**Comment by garronej** [comment]
Ok that's a good thing. To change a default I have to write a migration script...
