### ISSUE TITLE
La page de documentation pour la gestion des secrets est en 404

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFrLab/onyxia-web#247]
Sur la page de gestion des secrets (https://datalab.sspcloud.fr/my-secrets/<user>/), il y a un lien vers la documentation relative à cette fonctionnalité (https://docs.sspcloud.fr/onyxia-guide-avance/utiliser-des-variables-denvironnement).

Malheureusement, cette dernière page est en 404. 💀

**Comment by romaintailhurat** [comment]
Un petit _up_ : le bon URL est https://docs.sspcloud.fr/onyxia-guide/utiliser-des-variables-denvironnement.

**Comment by romaintailhurat** [comment]
Mise à jour simplissime, si c'est ok pour vous, je peux fournir une pull request. 😅

**Comment by fcomte** [comment]
oui vas y :)

**Comment by romaintailhurat** [comment]
Done: https://github.com/InseeFrLab/onyxia-web/pull/249
