### ISSUE TITLE
Préciser le format attendu pour le repository dans la config Git 

### ISSUE THREAD

**Issue by avouacr** [InseeFrLab/onyxia-web#259]
Dans la config Git à l'initialisation d'un service, le nom "Repository" est un peu trompeur (je m'y suis trompé, et d'autres aussi) : on s'attendrait à ne devoir mettre que le nom du repo ou à la limite username/repo, alors qu'il faut l'URL complète pour que ça fonctionne.

Je propose de remplacer "Repository" par "Repository URL" pour bien indiquer l'input attendu.

**Comment by garronej** [comment]
@fcomte
