### ISSUE TITLE
Edit button on saved config are not working ? not yet implemented? 

### ISSUE THREAD

**Issue by cthiounn** [InseeFrLab/onyxia-web#260]
I'm having an issue with the edit button on the saved config card. Is the feature properly working for anyone else ?

![image](https://user-images.githubusercontent.com/45511529/134770391-de899e16-dee7-4a55-9d56-3754d65d3448.png)

**Comment by garronej** [comment]
It's broken indeed... fixing.

**Comment by garronej** [comment]
@cthiounn it's fixed. Sorry for the long delay. I didn't noticed the issue.
