### ISSUE TITLE
Disable file & secrets management when not configured

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-web#261]
Hi,

Onyxia can be deployed minimalistically with no minio & secrets configured.  
We could disable file and secrets management menu buttons if `MINIO_URL` & `VAULT_URL` are not set (respectively).

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/136021728-460a131b-bfe6-4bcb-9074-9efc46eb3d0f.png)
