### ISSUE TITLE
Display an error if the API is unreachable

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-web#262]
Currently if the API fails to respond, the page is blank with an error in the console. Most users are not used to check the console for error. We may want to display a warning message on the screen to explain that the API URL is probably misconfigured.

**Comment by garronej** [comment]
![image](https://user-images.githubusercontent.com/6702424/136017942-552ecf7c-3860-4451-87c2-ccfd8f9e5e66.png)
