### ISSUE TITLE
Add a reset configuration feature at the service launcher

### ISSUE THREAD

**Issue by marchufschmitt** [InseeFrLab/onyxia-web#266]
Add a reset configuration button at the service configuration launcher : 

<img width="447" alt="Capture d’écran 2021-10-25 à 10 18 10" src="https://user-images.githubusercontent.com/62331119/138663350-d164fe71-3ca7-4797-a8b4-f1b3b6c4d44c.png">

**Comment by smith-julien** [comment]
After discussion with @olevitt , I move the reset button in the service launcher card.

![ReinitButton](https://user-images.githubusercontent.com/7826672/204272200-7290ec03-b1a0-4342-a4b5-d2b821ef6a45.PNG)
