### ISSUE TITLE
[Minor] bottom Vault copy UI-button does not seem to work

### ISSUE THREAD

**Issue by cthiounn** [InseeFrLab/onyxia-web#268]
The button on the bottom near the "Add a new variable" button does not copy the path into memory (the top button is working well)

![image](https://user-images.githubusercontent.com/45511529/140414658-4962356b-124c-4268-a3b7-54b3c5de13f2.png)

seems like the basename is "." in the explorer.tsx

**Comment by garronej** [comment]
Thank you for reporting I will investigate.

**Comment by garronej** [comment]
in the meantime, this button has the same effect: 
![image](https://user-images.githubusercontent.com/6702424/142344823-c4b6e69b-b2f9-4892-8d11-789b9d2210d4.png)

**Comment by garronej** [comment]
@cthiounn I think it's fixed. Thanks for reporting. Please reopen if if the issue resurface.
