### ISSUE TITLE
Change password link is deprecated

### ISSUE THREAD

**Issue by olevitt** [InseeFrLab/onyxia-web#270]
Hi,

Keycloak recently rewrote their account management page and the link /account/password we are using here : https://github.com/InseeFrLab/onyxia-web/blob/16f61a87a2020717297662aeec31cdaaad512304/src/app/components/pages/Account/tabs/AccountInfoTab.tsx#L88 
do not work (404) anymore on recent versions as they have "keycloak v2" as default account theme.  
Linking to /account instead of /account/password works on both themes and user can then navigate to 
the password change tab (or any other tab btw, it has much more features than changing the password).

I suggest we change /account/password to /account

**Comment by garronej** [comment]
Ah yes.

**Comment by marchufschmitt** [comment]
replace button text too : "Change account informations" / "Modifier les informations du compte
https://github.com/InseeFrLab/onyxia-web/edit/main/src/app/i18n/translations.ts#L167
https://github.com/InseeFrLab/onyxia-web/edit/main/src/app/i18n/translations.ts#L474

**Comment by garronej** [comment]
@olevitt Diogo @eurostat told me about the issue but I didn't understand.  
On our instance the link still works.... https://auth.lab.sspcloud.fr/auth/realms/sspcloud/account/password

**Comment by garronej** [comment]
Ok got it, we have a custom admin theme, that's why

**Comment by garronej** [comment]
Fixed
