### ISSUE TITLE
Use a rootless image

### ISSUE THREAD

**Issue by sathieu** [InseeFrLab/onyxia-web#271]
Current image is based on `nginx` which requires a root user and the following capabilities: `DAC_OVERRIDE`, `NET_BIND8SERVICE`, `SETGID` and `SETUID` (enabled by default).

[doc](https://hub.docker.com/_/nginx) as recommendation on *Running nginx as a non-root user*. 

> Alternatively, check out the official [Docker NGINX unprivileged image](https://hub.docker.com/r/nginxinc/nginx-unprivileged).

Proposed roadmap (to avoid hard binding between chart and image):

- [x] https://github.com/InseeFrLab/helm-charts/pull/24
- [x] https://github.com/InseeFrLab/onyxia-web/pull/273
- [ ] https://github.com/InseeFrLab/helm-charts/pull/26
- [ ] https://github.com/InseeFrLab/onyxia-web/pull/274

**Comment by garronej** [comment]
👍🏻

**Comment by garronej** [comment]
New releases, containing your update on the ngnix config have been published tonight.  
It you want your future changes to be published as soon as I merges them you should update the [`package.json`'s version number](https://github.com/InseeFrLab/onyxia-web/blob/595d8ae36de0b8a24e3e8b4c609423f6d33a11ca/package.json#L4)

**Comment by sathieu** [comment]
Merci @garronej.

Could you please review https://github.com/InseeFrLab/onyxia-api/pull/109 too?
