### ISSUE TITLE
Mauvaise redirection pour le service MLFlow lors du clic sur le bouton "Learn more"

### ISSUE THREAD

**Issue by Naxxos** [InseeFrLab/onyxia-web#275]
Bonjour,

Lorsque l'on clique sur "Learn more" pour le service ML Flow, nous sommes redirigés vers le site de Jupyter.

À modifier :
L'attribut "home" doit être  "https://mlflow.org"  dans la config de onyxia-web/public/samples/config_mlflow.json

**Comment by garronej** [comment]
@Naxxos thank you.

**Comment by garronej** [comment]
@Naxxos, just so you know, this information come from [the catalogue](https://github.com/InseeFrLab/helm-charts-datascience) that is independent from onyxia-web.  
[Fix](https://github.com/InseeFrLab/helm-charts-datascience/commit/61c5bf8e856a9072741f61c8ce7537a219b6acd8)
