### ISSUE TITLE
Can't copy Service Password on iPhone

### ISSUE THREAD

**Issue by ddecrulle** [InseeFrLab/onyxia-web#277]
Hello,

When I'm using my iPhone, I can not copy the service password directly in the page My Services.

When I click on copy I have the following alert : 

![image](https://user-images.githubusercontent.com/81740200/146793678-35ef3fe0-9cfb-4770-89d7-d8b2e391bddb.png)
(Tested on Safary 15.X and Chrome)

Howerver the copy works when I go on My Account / Password for your services.

**Comment by garronej** [comment]
Thank you for reporting!

**Comment by garronej** [comment]
Should be fixed, let me know if it isn't the case.  
Sorry for taking so long.
