### ISSUE TITLE
Language unsets after login

### ISSUE THREAD

**Issue by dmoreira97DLTT** [InseeFrLab/onyxia-web#295]
Hello,

We are currently working with the latest releases of both Onyxia-web and Onyxia-API. After logging in through our Keycloak instance the language becomes unset to neither English nor French and at that stage, the /my-services page does not load. Only after selecting one of the languages, does the platform works as expected with no other bugs.

Feel free to aks for any more info to reproduce this issue.

Thanks

**Comment by garronej** [comment]
Hi @dmoreira97DLTT,  
I fixed the bug this afternoon.  
You just need to update to the latest onxia-ui version and remove local storage.

**Comment by garronej** [comment]
https://user-images.githubusercontent.com/6702424/160457878-18989f79-91f1-4492-8871-16229213484b.mov

**Comment by dmoreira97DLTT** [comment]
Nice, thanks.
