### ISSUE TITLE
Running in the background

### ISSUE THREAD

**Issue by hdm30** [InseeFrLab/onyxia-web#299]
Hi,

I tried this tool to run deep learning models using tensorflow service. I'm wondering if there is a way to keep the instance active at night while my device is turned off ?! otherwise it won't be possible for complex models to be finished if the training takes so long.

Many thanks in advance.

**Comment by garronej** [comment]
Hi @hdm30,  
Of course you can leave the services running for as long as you see fit.  
After a while the s3 and vault token will expire though.  
It's 24 hours for the s3 token.

**Comment by hdm30** [comment]
Hi @garronej,

Thank you for your quick reply. I mean if the training takes more than 24 hours and my device turned off I won't be able to reopen the service since the s3 token has been expired right?

**Comment by garronej** [comment]
No, event if the token has expired you can still connect to your services. You just won't be able to use the S3 API.

**Comment by garronej** [comment]
That said you can always obtain a new S3 token manually.  
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/6702424/163991972-736206a4-b73b-4c29-bdda-54e85e163bd4.png">

My account -> connect to storage (tab) -> Init script, select "Environment variables" -> click on the download button ( the  arrow pointing down icon)  

You will download a file that contains the environment variables to update.

**Comment by hdm30** [comment]
I'm not sure I understand. For instance, I've just open tensorflow service i run deep learning model over there. I lost the connection so when it come back i tried to reopen the service but it didn't work i had this error "forbidden
![forbidden_error](https://user-images.githubusercontent.com/91948840/164009976-583fcc3a-b099-4768-9233-8637baa31baa.png)
"
in this case how should i proceed to restaure the service?

**Comment by garronej** [comment]
Ah, this is a security feature.  
You can only access your services from the IP you had when you launched the service.  
For example, if you start the service at your office then come back home you'll not be able to access your services at home.  
This restriction can be disabled when you launch the service.  
You have to uncheck "Enable IP protection"

<img width="1237" alt="image" src="https://user-images.githubusercontent.com/6702424/164011472-784880ab-9848-4cd9-bd48-92c220068fbc.png">

**Comment by hdm30** [comment]
yes it worked thank you
