### ISSUE TITLE
Latest version tag is unstable

### ISSUE THREAD

**Issue by kellianoy** [InseeFrLab/onyxia-web#311]
# Latest version tag is unstable

## Issue

When using the Helm chart to deploy Onyxia, the image defaults to the `Latest` tag, resulting in an error:

```json
Error: Wrong assertion encountered: ".s3.accessKeyId has no default value"
```

This error locks the screen in a permanent loop.

## Reproducibility

- Start Onyxia with all the components well parameterized (Keycloak, MinIO, Vault) with the Helm chart with default image
- Log in
- Try launching the vscode service

## Possible Fix 

Taking example from [keycloak](https://github.com/keycloak/keycloak/releases):

- Creating a new tag named `Nightly`, which allows for unstable/WIP versioning when developing
- Making `Latest` a version that we know is working, and is stable.

**Comment by garronej** [comment]
Thank for reporting @kellianoy,  

It was an error in the CI pipeline, is has been fixed.
